// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6JgZ2Iai831NQJhVQ-LE9b582jswlvEY',
    appId: '1:1006028968052:web:02aa9fe78eacd58dca0121',
    messagingSenderId: '1006028968052',
    projectId: 'mindcare-6eea7',
    authDomain: 'mindcare-6eea7.firebaseapp.com',
    storageBucket: 'mindcare-6eea7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD5YUOmIwOotdCZPmUwgpe3UIr5Lwb9Eg',
    appId: '1:1006028968052:android:22ee996cbfd294d3ca0121',
    messagingSenderId: '1006028968052',
    projectId: 'mindcare-6eea7',
    storageBucket: 'mindcare-6eea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHLAfZkiJQsPJ_TuBS2VUvyxivZNgUEfc',
    appId: '1:1006028968052:ios:1cd12f0f03e5d1f2ca0121',
    messagingSenderId: '1006028968052',
    projectId: 'mindcare-6eea7',
    storageBucket: 'mindcare-6eea7.firebasestorage.app',
    iosBundleId: 'com.example.mindcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHLAfZkiJQsPJ_TuBS2VUvyxivZNgUEfc',
    appId: '1:1006028968052:ios:1cd12f0f03e5d1f2ca0121',
    messagingSenderId: '1006028968052',
    projectId: 'mindcare-6eea7',
    storageBucket: 'mindcare-6eea7.firebasestorage.app',
    iosBundleId: 'com.example.mindcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6JgZ2Iai831NQJhVQ-LE9b582jswlvEY',
    appId: '1:1006028968052:web:d63fae334c457e98ca0121',
    messagingSenderId: '1006028968052',
    projectId: 'mindcare-6eea7',
    authDomain: 'mindcare-6eea7.firebaseapp.com',
    storageBucket: 'mindcare-6eea7.firebasestorage.app',
  );
}
